### ISSUE TITLE
kp.dat最新版1113，麻烦大神测试更新

### ISSUE THREAD

**Issue by Portan** [project-lede/koolproxy#2]
猴子大神更新了视频规则，是否可以更新到这里来？
[rules20211113.zip](https://github.com/project-lede/koolproxy/files/7533084/rules20211113.zip)

**Comment by project-lede** [comment]
已经更新。

**Comment by Portan** [comment]
[rules20211120.tar.gz](https://github.com/project-lede/koolproxy/files/7576182/rules20211120.tar.gz)
新的规则，麻烦大神测试更新。
